FROM my127/magento1-console:{{ @('php.version') }}-fpm-alpine

COPY .my127ws/docker/image/console/root /

ENV APP_MODE {{ @('app.mode') }}

{% if @('app.build') == 'static' %}
RUN chown build:build /app
COPY --chown=build:build .my127ws/skeleton       /home/build/skeleton
COPY --chown=build:build ./                      /app
USER build
RUN rm -rf /app/.my127ws
RUN app build pass-1
USER root
{% else %}
VOLUME /app
VOLUME /home/build/skeleton
{% endif %}

ENTRYPOINT /entrypoint.sh
