FROM my127/magento1-console:{{ @('php.version') }}-fpm-alpine

COPY .my127ws/docker/image/console/root /

ENV APP_MODE {{ @('app.mode') }}

{% if @('app.build') == 'static' %}

RUN chown build:build /app

# build - composer
#COPY --chown=build:build .my127ws/skeleton/auth.json composer.json composer.lock /app/
#USER build
#RUN composer install --no-scripts --no-autoloader && rm -rf /home/build/.composer/cache
#USER root

# build - application
COPY --chown=build:build .my127ws/skeleton       /home/build/skeleton
COPY --chown=build:build ./                      /app
USER build
RUN app build
USER root

{% else %}
VOLUME /app
VOLUME /home/build/skeleton
{% endif %}

ENTRYPOINT /entrypoint.sh
