{% if @('app.build') == 'static' %}
FROM {{ @('app.docker.repository') ~ ':' ~ @('app.version') }}-console as console
{% endif %}
FROM my127/magento1:{{ @('php.version') }}-fpm-alpine

WORKDIR /app

COPY root  /

{% if @('app.build') == 'static' %}
RUN chown www-data:www-data /app
COPY --from=console --chown=www-data:www-data /app /app
{% else %}
VOLUME /app
{% endif %}
ENV APP_MODE {{ @('app.mode') }}
